//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TercerParcialAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class avion
    {
        public int IdAvion { get; set; }
        public string NombreAvion { get; set; }
        public string marca { get; set; }
        public int capacidad { get; set; }
        public string descripcion { get; set; }
    }
}
